using System.Windows.Controls;
using System.Windows.Threading;

namespace OllamaDemo.Shared.Views
{
    /// <summary>
    /// Interaction logic for ExcelDataView.xaml
    /// </summary>
    public partial class ExcelDataView : UserControl
    {
        public ExcelDataView()
        {
            InitializeComponent();
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            if (sender is not DataGrid grid) { return; }
            grid.Dispatcher.InvokeAsync(() =>
            {
                foreach (var column in grid.Columns)
                {
                    if (column.ActualWidth > 250)
                    {
                        column.Width = 250;
                    }
                }
            }, DispatcherPriority.Loaded);
        }
    }
}
