using System.Windows.Controls;
using System.Windows.Threading;

namespace OllamaDemo.SemanticSearch.Views;

/// <summary>
/// Interaction logic for SemanticSearchView.xaml
/// </summary>
public partial class SemanticSearchView : UserControl
{
    public SemanticSearchView()
    {
        InitializeComponent();
    }

    private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
    {
        if (sender is not DataGrid grid) { return; }
        grid.Dispatcher.InvokeAsync(() =>
        {
            foreach (var column in grid.Columns)
            {
                if (column.ActualWidth > 500)
                {
                    column.Width = 500;
                }
            }
        }, DispatcherPriority.Loaded);
    }
}
